apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-api-path
  labels:
    name: support-api-path
spec:
  rules:
  - host: api.hypertheory.com
    http:
      paths:
      - pathType: Prefix
        path: "/helpdesk/support/"
        backend:
          service:
            name: support-api-service
            port: 
              number: 4200
